import { createContext, useContext, useState, useEffect, ReactNode } from "react";

type Language = "de" | "en";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, replacements?: Record<string, string | number>) => string;
}

const translations = {
  de: {
    // Navigation
    "nav.company": "Mein Unternehmen",
    "nav.search": "Partner finden",
    "nav.myPartners": "Meine Partner",
    "nav.messages": "Nachrichten",
    "nav.signOut": "Abmelden",
    
    // Common
    "common.loading": "Wird geladen...",
    "common.save": "Speichern",
    "common.cancel": "Abbrechen",
    "common.delete": "Löschen",
    "common.edit": "Bearbeiten",
    "common.search": "Suchen",
    "common.back": "Zurück",
    "common.next": "Weiter",
    "common.send": "Senden",
    "common.close": "Schließen",
    "common.viewProfile": "Profil ansehen",
    "common.chat": "Chat",
    "common.profile": "Profil",
    "common.filter": "Filter",
    "common.all": "Alle",
    "common.employees": "Mitarbeiter",
    "common.error": "Fehler",
    "common.success": "Erfolg",
    "common.noResults": "Keine Ergebnisse gefunden",
    "common.noDescription": "Keine Beschreibung",
    
    // Company Profile
    "company.title": "Unternehmensprofil",
    "company.yourProfile": "Ihr Unternehmensprofil",
    "company.name": "Unternehmensname",
    "company.industry": "Branche",
    "company.size": "Unternehmensgröße",
    "company.country": "Land",
    "company.city": "Stadt",
    "company.location": "Standort",
    "company.foundedYear": "Gründungsjahr",
    "company.founded": "Gegründet",
    "company.website": "Website",
    "company.description": "Beschreibung",
    "company.aboutCompany": "Über das Unternehmen",
    "company.offers": "Was wir anbieten",
    "company.lookingFor": "Was wir suchen",
    "company.cooperationType": "Kooperationsarten",
    "company.editProfile": "Profil bearbeiten",
    "company.updateInfo": "Aktualisieren Sie Ihre Unternehmensinformationen",
    "company.profileCreated": "Profil erstellt!",
    "company.profileCreatedDesc": "Ihr Unternehmensprofil wurde erfolgreich angelegt.",
    "company.profileUpdated": "Erfolgreich gespeichert",
    "company.profileUpdatedDesc": "Ihr Profil wurde aktualisiert.",
    "company.createProfile": "Erstellen Sie Ihr Unternehmensprofil, um zu starten.",
    "company.welcome": "Willkommen bei EuroConnect!",
    "company.loadError": "Profile konnten nicht geladen werden",
    "company.updateError": "Profil konnte nicht aktualisiert werden.",
    "company.allIndustries": "Alle Branchen",
    "company.allCountries": "Alle Länder",
    "company.firmName": "Firmenname",
    "company.required": "erforderlich",
    "company.optional": "optional",
    "company.characterLimit": "Zeichen",
    
    // Search
    "search.title": "Partner suchen",
    "search.aiSearch": "KI-Suche",
    "search.aiSupported": "KI-gestützte Suche und alle Partner",
    "search.placeholder": "Was suchen Sie? Beschreiben Sie Ihren idealen Partner...",
    "search.aiPlaceholder": "Beschreiben Sie einfach, was Sie suchen - z.B. \"CNC-Fräsdienstleister in Bayern\" oder \"Bio-zertifizierte Lebensmittellieferanten\"",
    "search.searching": "Suche...",
    "search.aiResults": "KI-Suchergebnisse",
    "search.allPartners": "Alle Partner",
    "search.results": "Suchergebnisse",
    "search.noResults": "Keine Partner gefunden. Versuchen Sie andere Filter.",
    "search.searchCompanies": "Suche nach Unternehmen...",
    "search.searchComplete": "Suche abgeschlossen",
    "search.companiesFound": "passende Unternehmen gefunden",
    "search.inputRequired": "Eingabe erforderlich",
    "search.enterQuery": "Bitte geben Sie eine Suchanfrage ein",
    "search.tryAgain": "Versuchen Sie eine andere Suchanfrage",
    "search.searchError": "Fehler bei der Suche",
    "search.match": "Match",
    "search.loadingPartners": "Lade Partner...",
    
    // Messages
    "messages.title": "Nachrichten",
    "messages.selectConversation": "Wählen Sie eine Konversation",
    "messages.typeMessage": "Nachricht eingeben...",
    "messages.noMessages": "Noch keine Nachrichten",
    "messages.translating": "Übersetze...",
    "messages.showOriginal": "Original zeigen",
    "messages.showTranslation": "Übersetzung zeigen",
    "messages.translate": "Übersetzen",
    "messages.lastMessage": "Letzte Nachricht",
    "messages.messagesCount": "Nachrichten",
    "messages.justNow": "Gerade eben",
    "messages.minutesAgo": "vor {count} Min.",
    "messages.hoursAgo": "vor {count} Std.",
    "messages.daysAgo": "vor {count} Tag",
    "messages.daysAgoPlural": "vor {count} Tagen",
    
    // Partners
    "partners.title": "Meine Partner",
    "partners.noPartners": "Noch keine Partner",
    "partners.noPartnersDesc": "Beginnen Sie mit der Suche nach passenden Partnern und nehmen Sie Kontakt auf",
    "partners.searchPartners": "Partner suchen",
    "partners.partnersConnected": "Partner mit denen Sie in Kontakt stehen",
    "partners.pending": "Ausstehend",
    "partners.accepted": "Akzeptiert",
    "partners.sendRequest": "Anfrage senden",
    "partners.accept": "Akzeptieren",
    "partners.reject": "Ablehnen",
    "partners.loadError": "Partner konnten nicht geladen werden",
    
    // Notifications
    "notifications.title": "Benachrichtigungen",
    "notifications.markAllRead": "Alle als gelesen markieren",
    "notifications.noNotifications": "Keine Benachrichtigungen",
    
    // Auth
    "auth.signIn": "Anmelden",
    "auth.signUp": "Registrieren",
    "auth.email": "E-Mail",
    "auth.password": "Passwort",
    "auth.forgotPassword": "Passwort vergessen?",
    "auth.backToHome": "Zurück zur Startseite",
    "auth.title": "EuroConnect",
    "auth.subtitle": "Ihr Zugang zum europäischen B2B-Netzwerk",
    "auth.emailPlaceholder": "firma@beispiel.de",
    "auth.passwordPlaceholder": "Mindestens 6 Zeichen",
    "auth.confirmPassword": "Passwort bestätigen",
    "auth.signInButton": "Anmelden",
    "auth.signingInButton": "Wird angemeldet...",
    "auth.signUpButton": "Kostenlos registrieren",
    "auth.signingUpButton": "Wird registriert...",
    "auth.termsText": "Mit der Registrierung stimmen Sie unseren Nutzungsbedingungen zu.",
    "auth.signInSuccess": "Erfolgreich angemeldet!",
    "auth.signInSuccessDescription": "Sie werden weitergeleitet.",
    "auth.signInError": "Anmeldung fehlgeschlagen",
    "auth.signInErrorDescription": "Bitte überprüfen Sie Ihre Anmeldedaten.",
    "auth.signUpSuccess": "Registrierung erfolgreich!",
    "auth.signUpSuccessDescription": "Sie werden weitergeleitet.",
    "auth.signUpError": "Registrierung fehlgeschlagen",
    "auth.signUpErrorDescription": "Bitte versuchen Sie es erneut.",
    "auth.passwordMismatch": "Passwörter stimmen nicht überein",
    "auth.passwordMismatchDescription": "Bitte überprüfen Sie Ihre Eingabe.",
    "auth.passwordTooShort": "Passwort zu kurz",
    "auth.passwordTooShortDescription": "Das Passwort muss mindestens 6 Zeichen lang sein.",
    
    // Home Page
    "home.heroSubtitle": "Stärken Sie den europäischen Binnenmarkt",
    "home.heroTitle": "Europäische KMUs",
    "home.heroTitleHighlight": "intelligent vernetzt",
    "home.heroDescription": "Beschreiben Sie einfach in natürlicher Sprache, was Sie suchen - unsere KI findet die perfekten Geschäftspartner in ganz Europa. Schnell, präzise und intelligent.",
    "home.startNow": "Jetzt kostenlos starten",
    "home.learnMore": "Mehr erfahren",
    "home.statsCompanies": "Unternehmen",
    "home.statsCountries": "EU-Länder",
    "home.statsConnections": "Verbindungen",
    "home.statsMatchRate": "Match-Rate",
    "home.featuresTitle": "Ihr Weg zu neuen",
    "home.featuresTitleHighlight": "Partnerschaften",
    "home.featuresSubtitle": "Intelligente Technologie trifft auf europäische Zusammenarbeit",
    "home.ctaTitle": "Bereit für europäische Zusammenarbeit?",
    "home.ctaDescription": "Werden Sie Teil des führenden B2B-Netzwerks für europäische KMUs",
    "home.ctaButton": "Kostenloses Unternehmensprofil erstellen",
    "home.footerCopyright": "© 2024 EuroConnect. Alle Rechte vorbehalten.",
    "home.aiSearchTitle": "KI-Partnersuche",
    "home.aiSearchDescription": "Beschreiben Sie in natürlicher Sprache, was Sie suchen. Unsere KI versteht Ihre Anfrage und findet die besten Matches.",
    "home.verifiedTitle": "Verifizierte Unternehmen",
    "home.verifiedDescription": "Alle Profile werden geprüft für maximale Sicherheit und Vertrauenswürdigkeit in Ihrer Geschäftsanbahnung.",
    "home.europeTitle": "Europaweit vernetzt",
    "home.europeDescription": "Zugang zu KMUs aus allen 27 EU-Mitgliedsstaaten plus UK, Norwegen und der Schweiz.",
    "home.partnershipsTitle": "Vielseitige Partnerschaften",
    "home.partnershipsDescription": "Ob Lieferant, Abnehmer oder Kooperationspartner – finden Sie die richtige Art der Zusammenarbeit.",
    "home.growthTitle": "Wachstum fördern",
    "home.growthDescription": "Erschließen Sie neue Märkte und stärken Sie Ihre Position im europäischen Binnenmarkt.",
    "home.intelligentSearchTitle": "Intelligente Suche",
    "home.intelligentSearchDescription": "Stellen Sie Fragen wie 'Ich suche CNC-Fräser in Bayern' - die KI findet automatisch passende Partner.",
    
    // AI Recommendations
    "aiRec.title": "KI-Empfehlungen",
    "aiRec.description": "Unsere KI analysiert Ihr Profil für personalisierte Partnervorschläge",
    "aiRec.analyzing": "KI analysiert passende Partner...",
    "aiRec.forYou": "KI-Empfehlungen für Sie",
    "aiRec.basedOnProfile": "Basierend auf Ihrem Profil und Ihrer Aktivität",
    "aiRec.refreshButton": "Aktualisieren",
    "aiRec.match": "{score}% Match",
    "aiRec.errorLoading": "Fehler beim Laden der Empfehlungen",
    "aiRec.retryButton": "Erneut versuchen",
    "aiRec.rateLimitError": "Ratenlimit erreicht",
    "aiRec.rateLimitDescription": "Bitte versuchen Sie es später erneut.",
    "aiRec.creditsError": "Credits erforderlich",
    "aiRec.creditsDescription": "Bitte fügen Sie Credits zu Ihrem Workspace hinzu.",
    "aiRec.loadError": "KI-Empfehlungen konnten nicht geladen werden.",
    
    // Partner Detail
    "partnerDetail.loadingProfile": "Lade Profil...",
    "partnerDetail.profileNotFound": "Profil nicht gefunden",
    "partnerDetail.backToSearch": "Zurück zur Suche",
    "partnerDetail.aboutCompany": "Über das Unternehmen",
    "partnerDetail.noDescription": "Keine Beschreibung verfügbar",
    "partnerDetail.industry": "Branche",
    "partnerDetail.location": "Standort",
    "partnerDetail.companySize": "Unternehmensgröße",
    "partnerDetail.employees": "Mitarbeiter",
    "partnerDetail.founded": "Gegründet",
    "partnerDetail.cooperationTypes": "Kooperationsarten",
    "partnerDetail.offers": "Bietet an",
    "partnerDetail.lookingFor": "Sucht",
    "partnerDetail.visitWebsite": "Website besuchen",
    "partnerDetail.contactTitle": "Kontakt aufnehmen",
    "partnerDetail.contactDescription": "Starten Sie einen Chat mit {companyName}",
    "partnerDetail.startChat": "Chat starten",
    
    // Profile Form
    "profileForm.title": "Unternehmensprofil erstellen",
    "profileForm.description": "Füllen Sie die Felder aus, um passende Partner zu finden",
    "profileForm.companyName": "Firmenname *",
    "profileForm.companyNamePlaceholder": "z.B. Mustermann GmbH",
    "profileForm.industry": "Branche *",
    "profileForm.industryDescription": "Wählen Sie alle zutreffenden Branchen",
    "profileForm.companySize": "Unternehmensgröße *",
    "profileForm.companySizePlaceholder": "Größe wählen",
    "profileForm.foundedYear": "Gründungsjahr",
    "profileForm.foundedYearPlaceholder": "z.B. 2010",
    "profileForm.country": "Land *",
    "profileForm.countryPlaceholder": "z.B. Deutschland",
    "profileForm.city": "Stadt *",
    "profileForm.cityPlaceholder": "z.B. Berlin",
    "profileForm.website": "Website",
    "profileForm.websitePlaceholder": "https://www.beispiel.de",
    "profileForm.companyDescription": "Unternehmensbeschreibung",
    "profileForm.descriptionPlaceholder": "Beschreiben Sie Ihr Unternehmen (max. 500 Zeichen)...",
    "profileForm.charactersCount": "{count}/500 Zeichen",
    "profileForm.offers": "Was bieten Sie an?",
    "profileForm.offersPlaceholder": "z.B. CNC-Bearbeitung, Beratung, Software-Entwicklung",
    "profileForm.offersDescription": "Komma-getrennte Tags",
    "profileForm.lookingFor": "Was suchen Sie?",
    "profileForm.lookingForPlaceholder": "z.B. Lieferanten, Vertriebspartner, Technologie-Partner",
    "profileForm.lookingForDescription": "Komma-getrennte Tags",
    "profileForm.cooperationType": "Art der Kooperation *",
    "profileForm.cooperationTypeDescription": "Wählen Sie alle zutreffenden Optionen",
    "profileForm.submitButton": "Profil erstellen",
    "profileForm.submittingButton": "Wird erstellt...",
    "profileForm.errorTitle": "Fehler",
    "profileForm.errorDescription": "Profil konnte nicht erstellt werden.",
    "profileForm.employeesLabel": "Mitarbeiter",
  },
  en: {
    // Navigation
    "nav.company": "My Company",
    "nav.search": "Find Partners",
    "nav.myPartners": "My Partners",
    "nav.messages": "Messages",
    "nav.signOut": "Sign Out",
    
    // Common
    "common.loading": "Loading...",
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.delete": "Delete",
    "common.edit": "Edit",
    "common.search": "Search",
    "common.back": "Back",
    "common.next": "Next",
    "common.send": "Send",
    "common.close": "Close",
    "common.viewProfile": "View Profile",
    "common.chat": "Chat",
    "common.profile": "Profile",
    "common.filter": "Filter",
    "common.all": "All",
    "common.employees": "Employees",
    "common.error": "Error",
    "common.success": "Success",
    "common.noResults": "No results found",
    "common.noDescription": "No description",
    
    // Company Profile
    "company.title": "Company Profile",
    "company.yourProfile": "Your Company Profile",
    "company.name": "Company Name",
    "company.industry": "Industry",
    "company.size": "Company Size",
    "company.country": "Country",
    "company.city": "City",
    "company.location": "Location",
    "company.foundedYear": "Founded Year",
    "company.founded": "Founded",
    "company.website": "Website",
    "company.description": "Description",
    "company.aboutCompany": "About the Company",
    "company.offers": "What We Offer",
    "company.lookingFor": "What We're Looking For",
    "company.cooperationType": "Cooperation Types",
    "company.editProfile": "Edit Profile",
    "company.updateInfo": "Update your company information",
    "company.profileCreated": "Profile Created!",
    "company.profileCreatedDesc": "Your company profile has been successfully created.",
    "company.profileUpdated": "Successfully Saved",
    "company.profileUpdatedDesc": "Your profile has been updated.",
    "company.createProfile": "Create your company profile to get started.",
    "company.welcome": "Welcome to EuroConnect!",
    "company.loadError": "Profiles could not be loaded",
    "company.updateError": "Profile could not be updated.",
    "company.allIndustries": "All Industries",
    "company.allCountries": "All Countries",
    "company.firmName": "Company Name",
    "company.required": "required",
    "company.optional": "optional",
    "company.characterLimit": "characters",
    
    // Search
    "search.title": "Search Partners",
    "search.aiSearch": "AI Search",
    "search.aiSupported": "AI-powered search and all partners",
    "search.placeholder": "What are you looking for? Describe your ideal partner...",
    "search.aiPlaceholder": "Simply describe what you're looking for - e.g. \"CNC milling service provider in Bavaria\" or \"Organic certified food suppliers\"",
    "search.searching": "Searching...",
    "search.aiResults": "AI Search Results",
    "search.allPartners": "All Partners",
    "search.results": "Search Results",
    "search.noResults": "No partners found. Try different filters.",
    "search.searchCompanies": "Search for companies...",
    "search.searchComplete": "Search Complete",
    "search.companiesFound": "matching companies found",
    "search.inputRequired": "Input Required",
    "search.enterQuery": "Please enter a search query",
    "search.tryAgain": "Try a different search query",
    "search.searchError": "Search Error",
    "search.match": "Match",
    "search.loadingPartners": "Loading Partners...",
    
    // Messages
    "messages.title": "Messages",
    "messages.selectConversation": "Select a conversation",
    "messages.typeMessage": "Type a message...",
    "messages.noMessages": "No messages yet",
    "messages.translating": "Translating...",
    "messages.showOriginal": "Show Original",
    "messages.showTranslation": "Show Translation",
    "messages.translate": "Translate",
    "messages.lastMessage": "Last Message",
    "messages.messagesCount": "Messages",
    "messages.justNow": "Just now",
    "messages.minutesAgo": "{count} min. ago",
    "messages.hoursAgo": "{count} hrs. ago",
    "messages.daysAgo": "{count} day ago",
    "messages.daysAgoPlural": "{count} days ago",
    
    // Partners
    "partners.title": "My Partners",
    "partners.noPartners": "No partners yet",
    "partners.noPartnersDesc": "Start searching for suitable partners and get in touch",
    "partners.searchPartners": "Search Partners",
    "partners.partnersConnected": "partners you're connected with",
    "partners.pending": "Pending",
    "partners.accepted": "Accepted",
    "partners.sendRequest": "Send Request",
    "partners.accept": "Accept",
    "partners.reject": "Reject",
    "partners.loadError": "Partners could not be loaded",
    
    // Notifications
    "notifications.title": "Notifications",
    "notifications.markAllRead": "Mark all as read",
    "notifications.noNotifications": "No notifications",
    
    // Auth
    "auth.signIn": "Sign In",
    "auth.signUp": "Sign Up",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.forgotPassword": "Forgot Password?",
    "auth.backToHome": "Back to Home",
    "auth.title": "EuroConnect",
    "auth.subtitle": "Your Gateway to the European B2B Network",
    "auth.emailPlaceholder": "company@example.com",
    "auth.passwordPlaceholder": "At least 6 characters",
    "auth.confirmPassword": "Confirm Password",
    "auth.signInButton": "Sign In",
    "auth.signingInButton": "Signing in...",
    "auth.signUpButton": "Register for free",
    "auth.signingUpButton": "Registering...",
    "auth.termsText": "By registering, you agree to our Terms of Service.",
    "auth.signInSuccess": "Successfully signed in!",
    "auth.signInSuccessDescription": "You will be redirected.",
    "auth.signInError": "Sign in failed",
    "auth.signInErrorDescription": "Please check your credentials.",
    "auth.signUpSuccess": "Registration successful!",
    "auth.signUpSuccessDescription": "You will be redirected.",
    "auth.signUpError": "Registration failed",
    "auth.signUpErrorDescription": "Please try again.",
    "auth.passwordMismatch": "Passwords do not match",
    "auth.passwordMismatchDescription": "Please check your input.",
    "auth.passwordTooShort": "Password too short",
    "auth.passwordTooShortDescription": "Password must be at least 6 characters long.",
    
    // Home Page
    "home.heroSubtitle": "Strengthen the European Single Market",
    "home.heroTitle": "European SMEs",
    "home.heroTitleHighlight": "intelligently connected",
    "home.heroDescription": "Simply describe what you're looking for in natural language - our AI finds the perfect business partners across Europe. Fast, precise and intelligent.",
    "home.startNow": "Start for free now",
    "home.learnMore": "Learn more",
    "home.statsCompanies": "Companies",
    "home.statsCountries": "EU Countries",
    "home.statsConnections": "Connections",
    "home.statsMatchRate": "Match Rate",
    "home.featuresTitle": "Your Path to New",
    "home.featuresTitleHighlight": "Partnerships",
    "home.featuresSubtitle": "Intelligent technology meets European collaboration",
    "home.ctaTitle": "Ready for European Cooperation?",
    "home.ctaDescription": "Become part of the leading B2B network for European SMEs",
    "home.ctaButton": "Create Free Company Profile",
    "home.footerCopyright": "© 2024 EuroConnect. All rights reserved.",
    "home.aiSearchTitle": "AI Partner Search",
    "home.aiSearchDescription": "Describe in natural language what you're looking for. Our AI understands your query and finds the best matches.",
    "home.verifiedTitle": "Verified Companies",
    "home.verifiedDescription": "All profiles are reviewed for maximum security and trustworthiness in your business dealings.",
    "home.europeTitle": "Connected Across Europe",
    "home.europeDescription": "Access to SMEs from all 27 EU member states plus UK, Norway and Switzerland.",
    "home.partnershipsTitle": "Versatile Partnerships",
    "home.partnershipsDescription": "Whether supplier, buyer or cooperation partner – find the right type of collaboration.",
    "home.growthTitle": "Foster Growth",
    "home.growthDescription": "Open up new markets and strengthen your position in the European single market.",
    "home.intelligentSearchTitle": "Intelligent Search",
    "home.intelligentSearchDescription": "Ask questions like 'I'm looking for CNC milling services in Bavaria' - the AI automatically finds suitable partners.",
    
    // AI Recommendations
    "aiRec.title": "AI Recommendations",
    "aiRec.description": "Our AI analyzes your profile for personalized partner suggestions",
    "aiRec.analyzing": "AI is analyzing suitable partners...",
    "aiRec.forYou": "AI Recommendations for You",
    "aiRec.basedOnProfile": "Based on your profile and activity",
    "aiRec.refreshButton": "Refresh",
    "aiRec.match": "{score}% Match",
    "aiRec.errorLoading": "Error loading recommendations",
    "aiRec.retryButton": "Try again",
    "aiRec.rateLimitError": "Rate limit reached",
    "aiRec.rateLimitDescription": "Please try again later.",
    "aiRec.creditsError": "Credits required",
    "aiRec.creditsDescription": "Please add credits to your workspace.",
    "aiRec.loadError": "AI recommendations could not be loaded.",
    
    // Partner Detail
    "partnerDetail.loadingProfile": "Loading profile...",
    "partnerDetail.profileNotFound": "Profile not found",
    "partnerDetail.backToSearch": "Back to search",
    "partnerDetail.aboutCompany": "About the Company",
    "partnerDetail.noDescription": "No description available",
    "partnerDetail.industry": "Industry",
    "partnerDetail.location": "Location",
    "partnerDetail.companySize": "Company Size",
    "partnerDetail.employees": "Employees",
    "partnerDetail.founded": "Founded",
    "partnerDetail.cooperationTypes": "Cooperation Types",
    "partnerDetail.offers": "Offers",
    "partnerDetail.lookingFor": "Looking For",
    "partnerDetail.visitWebsite": "Visit Website",
    "partnerDetail.contactTitle": "Get in Touch",
    "partnerDetail.contactDescription": "Start a chat with {companyName}",
    "partnerDetail.startChat": "Start Chat",
    
    // Profile Form
    "profileForm.title": "Create Company Profile",
    "profileForm.description": "Fill in the fields to find suitable partners",
    "profileForm.companyName": "Company Name *",
    "profileForm.companyNamePlaceholder": "e.g. Example Corp",
    "profileForm.industry": "Industry *",
    "profileForm.industryDescription": "Select all applicable industries",
    "profileForm.companySize": "Company Size *",
    "profileForm.companySizePlaceholder": "Select size",
    "profileForm.foundedYear": "Founded Year",
    "profileForm.foundedYearPlaceholder": "e.g. 2010",
    "profileForm.country": "Country *",
    "profileForm.countryPlaceholder": "e.g. Germany",
    "profileForm.city": "City *",
    "profileForm.cityPlaceholder": "e.g. Berlin",
    "profileForm.website": "Website",
    "profileForm.websitePlaceholder": "https://www.example.com",
    "profileForm.companyDescription": "Company Description",
    "profileForm.descriptionPlaceholder": "Describe your company (max. 500 characters)...",
    "profileForm.charactersCount": "{count}/500 characters",
    "profileForm.offers": "What do you offer?",
    "profileForm.offersPlaceholder": "e.g. CNC machining, Consulting, Software Development",
    "profileForm.offersDescription": "Comma-separated tags",
    "profileForm.lookingFor": "What are you looking for?",
    "profileForm.lookingForPlaceholder": "e.g. Suppliers, Sales Partners, Technology Partners",
    "profileForm.lookingForDescription": "Comma-separated tags",
    "profileForm.cooperationType": "Type of Cooperation *",
    "profileForm.cooperationTypeDescription": "Select all applicable options",
    "profileForm.submitButton": "Create Profile",
    "profileForm.submittingButton": "Creating...",
    "profileForm.errorTitle": "Error",
    "profileForm.errorDescription": "Profile could not be created.",
    "profileForm.employeesLabel": "Employees",
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("language");
    return (saved === "en" || saved === "de") ? saved : "de";
  });

  useEffect(() => {
    localStorage.setItem("language", language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string, replacements?: Record<string, string | number>): string => {
    let text = translations[language][key as keyof typeof translations.de] || key;
    
    if (replacements) {
      Object.entries(replacements).forEach(([placeholder, value]) => {
        text = text.replace(`{${placeholder}}`, String(value));
      });
    }
    
    return text;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
};
